const artistes = [
  {
    id: "johnnyHallyday",
    name: "Johnny Hallyday",
    logo: "/images/hobbies/artistes/JohnnyHallydayLogo.png",
    lien: "/hobbies/artistes/johnnyHallyday",
    description:
      "Johnny Hallyday, de son vrai nom Jean-Philippe Smet, est un chanteur, compositeur et acteur français, né le 15 juin 1943 à Paris 9e arr. et mort le 5 décembre 2017 à Marnes-la-Coquette (Hauts-de-Seine).Durant ses 57 ans de carrière, il s'impose comme l'un des plus célèbres chanteurs francophones et l'une des personnalités les plus présentes dans le paysage médiatique français.S'il n'est pas le premier à chanter du rock en France, il est, à partir de 1960, le premier à populariser le genre dans l'Hexagone. Bien qu'il ait interprété de nombreuses ballades sentimentales et des airs country au cours de sa carrière, le rock reste sa principale référence au travers de ses différents courants, puisant tous leurs origines dans le blues : rock 'n' roll, rhythm and blues, soul, rock psychédélique, soft rock ou encore pop rock.Sa longévité au premier plan de la scène artistique et ses prestations vocales et scéniques lui attirent la reconnaissance de ses pairs et du public. Au total, il réalise 80 albums, dont 51 albums studio. Il totalise 6 disques de diamant, 40 disques d'or, 22 disques de platine et 10 Victoires de la musique. En dehors des pays francophones, s'il ne parvint pas à s'imposer durablement malgré plusieurs tournées à succès, notamment en Amérique du Sud, sa réputation d'homme de scène franchit en revanche les frontières. Il effectue ainsi 184 tournées et donne plus de 3 250 concerts, totalisant près de 30 millions de spectateurs, avec des prestations à gros budgets et effets scéniques. Alors qu'il est atteint d'un cancer du poumon, il effectue sa dernière tournée en juin et juillet 2017, aux côtés de ses amis Jacques Dutronc et Eddy Mitchell, avec qui il a formé le trio des Vieilles Canailles. Sa mort, survenue quelques mois plus tard des suites de sa maladie, donne lieu à un important hommage populaire. Au moment de sa mort, les ventes de ses disques se chiffrent à 110 millions d'exemplaires.",
  },
  {
    id: "SimonAndGargunkel",
    name: "Simon & Garfunkel",
    logo: "/images/hobbies/artistes/Simon&GarfunkelLogo.png",
    lien: "/hobbies/artistes/SimonAndGargunkel",
    description:
      "Simon and Garfunkel [ˈsaɪmən ən gɑrfʌnkəl]1 est un duo américain de folk rock, originaire de Forest Hills, dans le Queens, à New York. Il est constitué du guitariste et auteur-compositeur-interprète Paul Simon et du chanteur Arthur Garfunkel. Tous deux se rencontrent pour la première fois dans le Queens en 1953. Ils apprennent à s'accorder l'un avec l'autre et commencent à écrire leurs propres compositions. Ils connaissent leur premier succès en 1957, sous le nom de Tom and Jerry, avec la chanson Hey Schoolgirl, qui imite le style de leurs idoles The Everly Brothers. Mais ce succès n'est pas confirmé et ils poursuivent ensuite leurs études universitaires, chacun de son côté. Ils se retrouvent en 1963, avec un intérêt accru pour la musique folk, et signent un contrat avec Columbia Records. Leur premier album, Wednesday Morning, 3 A.M. (1964), est un échec commercial à sa sortie et le duo se sépare, Simon décidant de poursuivre sa carrière en solo en Angleterre.Cependant, une nouvelle version de leur chanson The Sound of Silence connaît le succès sur les ondes américaines en 1965 et atteint la première place du Billboard Hot 100. Le duo se reforme alors et enregistre un deuxième album, Sounds of Silence (1966), qui est rapidement suivi par Parsley, Sage, Rosemary and Thyme (1966), album sur lequel le duo prend un plus grand contrôle créatif. La popularité du duo s'accroît avec la bande originale du film Le Lauréat (1967), composée en majeure partie par leurs chansons. Leur album suivant, Bookends (1968), les propulse au rang de stars internationales majeures. Néanmoins, les relations entre les deux hommes se dégradent et le duo se sépare peu après la sortie de leur album suivant, Bridge over Troubled Water (1970), qui est leur plus grand succès commercial. Dans une interview télévisée, Simon déclarera qu'il avait composé Bridge Over Troubled Water pour Garfunkel et qu'il ne voyait que lui pour l'interpréter. Lorsque Garfunkel commence les sessions, Simon est émerveillé par son interprétation mais il dira ressentir également un sentiment d'injustice devant cet accaparement : 'et l'auteur ?...'Simon and Garfunkel comptent parmi les artistes les plus populaires des années 1960 et sont considérés comme des icônes de la contre-culture de cette décennie, au même titre que les Beatles et Bob Dylan. Leurs chansons les plus célèbres, The Sound of Silence, I Am a Rock, Homeward Bound, Scarborough Fair/Canticle, A Hazy Shade of Winter, Mrs. Robinson, Bridge over Troubled Water, The Boxer, Cecilia et El Cóndor Pasa (If I Could), ont toutes connu un très grand succès international. Depuis leur séparation, Simon et Garfunkel ont reformé plusieurs fois le duo, notamment à l'occasion d'un concert à Central Park en 1981 qui réunit plus de 500 000 spectateurs, ce qui constitue l'une des plus grandes affluences de tous les temps pour un concert.",
  },
  {
    id: "era",
    name: "Era",
    logo: "/images/hobbies/artistes/eraLogo.png",
    lien: "/hobbies/artistes/era",
    description:
      "Era (stylisé +eRa+) est un projet musical fondé par le musicien français Éric Lévi, ancien membre du groupe rock Shakin' Street. Le troisième album sorti en 2003, The Mass, dans une inspiration proche de Carmina Burana, a connu un grand succès commercial en mélangeant des thèmes de musique originale interprétés par une chorale (chantant en un langage inventé), avec guitare électrique, cordes et synthétiseurs ; musique qu'on pourrait qualifier de new age1,2.L'univers visuel d'Era est le pendant de son inspiration musicale, il utilise des signes et des sentiments proches du religieux et de l'univers médiéval. Il explore une dimension universelle, un univers d'émotions, spirituel et mystique. Les chansons d'Era sont en une langue imaginaire proche du latin médiéval et en diverses autres langues, comme l'anglais ou l'arabe.",
  },
];
export { artistes };
